//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click settings..
        /// </summary>
        internal static string ClickSettings {
            get {
                return ResourceManager.GetString("ClickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dsn={0};Uid={1};Pwd={2};.
        /// </summary>
        internal static string ConnectionFormatODBC {
            get {
                return ResourceManager.GetString("ConnectionFormatODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=OraOLEDB.Oracle;Data Source=(DESCRIPTION=(CID=GTU_APP)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST={0})(PORT={1})))(CONNECT_DATA=(SID={2})(SERVER=DEDICATED)));User Id={3};Password={4};.
        /// </summary>
        internal static string ConnectionFormatOracle {
            get {
                return ResourceManager.GetString("ConnectionFormatOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=GAFOLEDB.ArcSDE.1;Location={0};Data Source={1}@{2};User Id={3};Password={4};.
        /// </summary>
        internal static string ConnectionFormatSDE {
            get {
                return ResourceManager.GetString("ConnectionFormatSDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect [ODBC].
        /// </summary>
        internal static string DisconnectODBC {
            get {
                return ResourceManager.GetString("DisconnectODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect [OLEDB].
        /// </summary>
        internal static string DisconnectOLEDB {
            get {
                return ResourceManager.GetString("DisconnectOLEDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Ifxoledbc.2;User ID={2};password={3};Data Source={1}@{0};Persist Security Info=true.
        /// </summary>
        internal static string InformixConnectionFormat {
            get {
                return ResourceManager.GetString("InformixConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lafis.
        /// </summary>
        internal static string InformixDefaultInstance {
            get {
                return ResourceManager.GetString("InformixDefaultInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informix.
        /// </summary>
        internal static string InformixDefaultPassword {
            get {
                return ResourceManager.GetString("InformixDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string InformixDefaultServer {
            get {
                return ResourceManager.GetString("InformixDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informix.
        /// </summary>
        internal static string InformixDefaultUser {
            get {
                return ResourceManager.GetString("InformixDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string InformixOptionInstance {
            get {
                return ResourceManager.GetString("InformixOptionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string InformixOptionPassword {
            get {
                return ResourceManager.GetString("InformixOptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string InformixOptionServer {
            get {
                return ResourceManager.GetString("InformixOptionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string InformixOptionUser {
            get {
                return ResourceManager.GetString("InformixOptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ms {
            get {
                object obj = ResourceManager.GetObject("ms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mssql {
            get {
                object obj = ResourceManager.GetObject("mssql", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\ODBC\ODBC.INI\ODBC Data Sources.
        /// </summary>
        internal static string ODBCDataSourcesRegKey {
            get {
                return ResourceManager.GetString("ODBCDataSourcesRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OdbcDefaultDSN {
            get {
                return ResourceManager.GetString("OdbcDefaultDSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informix.
        /// </summary>
        internal static string OdbcDefaultPID {
            get {
                return ResourceManager.GetString("OdbcDefaultPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informix.
        /// </summary>
        internal static string OdbcDefaultUID {
            get {
                return ResourceManager.GetString("OdbcDefaultUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSN.
        /// </summary>
        internal static string OdbcOptionDSN {
            get {
                return ResourceManager.GetString("OdbcOptionDSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        internal static string OdbcOptionPID {
            get {
                return ResourceManager.GetString("OdbcOptionPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        internal static string OdbcOptionUID {
            get {
                return ResourceManager.GetString("OdbcOptionUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lafis.
        /// </summary>
        internal static string OracleDefaultDatabase {
            get {
                return ResourceManager.GetString("OracleDefaultDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string OracleDefaultPassword {
            get {
                return ResourceManager.GetString("OracleDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1521.
        /// </summary>
        internal static string OracleDefaultPort {
            get {
                return ResourceManager.GetString("OracleDefaultPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string OracleDefaultServer {
            get {
                return ResourceManager.GetString("OracleDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orcl.
        /// </summary>
        internal static string OracleDefaultSid {
            get {
                return ResourceManager.GetString("OracleDefaultSid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lafisadmin.
        /// </summary>
        internal static string OracleDefaultUser {
            get {
                return ResourceManager.GetString("OracleDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATABASE.
        /// </summary>
        internal static string OracleOptionDb {
            get {
                return ResourceManager.GetString("OracleOptionDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string OracleOptionPassword {
            get {
                return ResourceManager.GetString("OracleOptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string OracleOptionPort {
            get {
                return ResourceManager.GetString("OracleOptionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string OracleOptionServer {
            get {
                return ResourceManager.GetString("OracleOptionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SID.
        /// </summary>
        internal static string OracleOptionSID {
            get {
                return ResourceManager.GetString("OracleOptionSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string OracleOptionUser {
            get {
                return ResourceManager.GetString("OracleOptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options\Informix.
        /// </summary>
        internal static string RegKeyOptionsInformix {
            get {
                return ResourceManager.GetString("RegKeyOptionsInformix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options\ODBC.
        /// </summary>
        internal static string RegKeyOptionsODBC {
            get {
                return ResourceManager.GetString("RegKeyOptionsODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options\Oracle.
        /// </summary>
        internal static string RegKeyOptionsOracle {
            get {
                return ResourceManager.GetString("RegKeyOptionsOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options\SDE.
        /// </summary>
        internal static string RegKeyOptionsSDE {
            get {
                return ResourceManager.GetString("RegKeyOptionsSDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options\SQL.
        /// </summary>
        internal static string RegKeyOptionsSQL {
            get {
                return ResourceManager.GetString("RegKeyOptionsSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lafis.
        /// </summary>
        internal static string SdeDefaultInstance {
            get {
                return ResourceManager.GetString("SdeDefaultInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sde.
        /// </summary>
        internal static string SdeDefaultPassword {
            get {
                return ResourceManager.GetString("SdeDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string SdeDefaultServer {
            get {
                return ResourceManager.GetString("SdeDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5152.
        /// </summary>
        internal static string SdeDefaultService {
            get {
                return ResourceManager.GetString("SdeDefaultService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sde.
        /// </summary>
        internal static string SdeDefaultUser {
            get {
                return ResourceManager.GetString("SdeDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string SdeOptionInstance {
            get {
                return ResourceManager.GetString("SdeOptionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SdeOptionPassword {
            get {
                return ResourceManager.GetString("SdeOptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string SdeOptionServer {
            get {
                return ResourceManager.GetString("SdeOptionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string SdeOptionService {
            get {
                return ResourceManager.GetString("SdeOptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SdeOptionUser {
            get {
                return ResourceManager.GetString("SdeOptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=sqloledb;Data Source={0};Initial Catalog={1};User Id={2};Password={3};.
        /// </summary>
        internal static string SqlConnectionFormat {
            get {
                return ResourceManager.GetString("SqlConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master.
        /// </summary>
        internal static string SqlDefaultInstance {
            get {
                return ResourceManager.GetString("SqlDefaultInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string SqlDefaultPassword {
            get {
                return ResourceManager.GetString("SqlDefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string SqlDefaultServer {
            get {
                return ResourceManager.GetString("SqlDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string SqlDefaultUser {
            get {
                return ResourceManager.GetString("SqlDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL files (*.sql)|*.sql|All files (*.*)|*.*.
        /// </summary>
        internal static string SQLFilesFilter {
            get {
                return ResourceManager.GetString("SQLFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string SqlOptionInstance {
            get {
                return ResourceManager.GetString("SqlOptionInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SqlOptionPassword {
            get {
                return ResourceManager.GetString("SqlOptionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string SqlOptionServer {
            get {
                return ResourceManager.GetString("SqlOptionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string SqlOptionUser {
            get {
                return ResourceManager.GetString("SqlOptionUser", resourceCulture);
            }
        }
    }
}
